### ISSUE TITLE
执行docker-compose up --build -d，运行错误

### ISSUE THREAD

**Issue by MisteryLiuCode** [cjhahaha/leetcode-compete#1]
=> ERROR [builder 8/8] RUN npm run build                                 15.1s
------
 > [builder 8/8] RUN npm run build:
#0 0.371 
#0 0.371 > leetcode-compete@0.1.0 build
#0 0.371 > react-scripts build
#0 0.371 
#0 0.695 The following changes are being made to your tsconfig.json file:
#0 0.696   - compilerOptions.jsx must be preserve (JSX is compiled by Babel)
#0 0.696 
#0 1.248 Creating an optimized production build...
#0 4.120 `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
#0 4.120     at isModuleDeclaration (/app/node_modules/@babel/types/lib/validators/generated/index.js:3940:35)
#0 4.120     at NodePath.<computed> [as isModuleDeclaration] (/app/node_modules/@babel/traverse/lib/path/index.js:181:12)
#0 14.84 Failed to compile.
#0 14.84 
#0 14.84 ./src/common/data_center/requests/check_user.ts 1:11471
#0 14.84 Module parse failed: Unexpected token (1:11471)
#0 14.84 You may need an appropriate loader to handle this file type.

**Comment by keyi6** [comment]
fixed in main branch
